name: Wooly
deploymentTarget: 11.0
options:
  bundleIdPrefix: com.kylebashour
settings:
  DEVELOPMENT_TEAM: ZEAD23GG77
  SWIFT_VERSION: 4.2
targets:
  Wooly:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - WoolyTests
    sources: 
      - path: Modules/Wooly/Sources
        name: Wooly
    name: Wooly
    dependencies:
      - target: Mammut
  WoolyTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - path: Modules/Wooly/Tests
        name: WoolyTests
    dependencies:
      - target: Wooly
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Wooly.app/Wooly
  Mammut:
    type: framework
    platform: iOS
    sources: 
      - path: Modules/Mammut/Sources
        name: Mammut
    dependencies:
      - carthage: Siesta
  Keychain:
    type: framework
    platform: iOS
    testTargets:
        - KeychainTests
    sources: 
      - path: Modules/Keychain/Sources
        name: Keychain
  KeychainTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - path: Modules/Keychain/Tests
        name: KeychainTests
    dependencies:
      - target: Keychain
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Wooly.app/Wooly
