name: Wooly
deploymentTarget: 11.0
options:
  bundleIdPrefix: com.kylebashour
settings:
  DEVELOPMENT_TEAM: ZEAD23GG77
  SWIFT_VERSION: 4.2
targets:
  Wooly:
    type: application
    platform: iOS
    sources: 
      - Sources/Wooly
    dependencies:
      - target: Mammut
  WoolyTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - Tests/WoolyTests
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Wooly.app/Wooly
  Mammut:
    type: framework
    platform: iOS
    sources: 
      - Sources/Mammut
