name: Wooly
options:
  bundleIdPrefix: com.kylebashour
settings:
  DEVELOPMENT_TEAM: ZEAD23GG77
  IPHONEOS_DEPLOYMENT_TARGET: 11.3
targets:
  Wooly:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - WoolyTests
    sources: 
      - path: Modules/Wooly/Sources
        name: Wooly
    name: Wooly
    dependencies:
      - target: Mammut
      - target: Keychain
      - carthage: PINCache
      - carthage: PINRemoteImage
      - carthage: AsyncDisplayKit
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      TARGETED_DEVICE_FAMILY: 1
  WoolyTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - path: Modules/Wooly/Tests
        name: WoolyTests
    dependencies:
      - target: Wooly
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Wooly.app/Wooly
  Mammut:
    type: framework
    platform: iOS
    sources: 
      - path: Modules/Mammut/Sources
        name: Mammut
    dependencies:
      - carthage: Siesta
      - target: Keychain
  Keychain:
    type: framework
    platform: iOS
    testTargets:
        - KeychainTests
    sources: 
      - path: Modules/Keychain/Sources
        name: Keychain
  KeychainTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - path: Modules/Keychain/Tests
        name: KeychainTests
    dependencies:
      - target: Keychain
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Wooly.app/Wooly
