name: Wooly
options:
  bundleIdPrefix: com.kylebashour
settings:
  CODE_SIGN_IDENTITY: iPhone Developer
  DEVELOPMENT_TEAM: ZEAD23GG77
  IPHONEOS_DEPLOYMENT_TARGET: 11.3
  SWIFT_VERSION: 4.2
targets:
  Wooly:
    type: application
    platform: iOS
    scheme:
      testTargets:
        - WoolyTests
    sources: 
      - path: Wooly
    name: Wooly
    dependencies:
      - carthage: Siesta
      - carthage: PINCache
      - carthage: PINRemoteImage
      - carthage: HTMLString
    settings:
      VERSIONING_SYSTEM: Apple Generic
      CURRENT_PROJECT_VERSION: 1
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      TARGETED_DEVICE_FAMILY: 1
  WoolyTests:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    sources:
      - path: Tests
    dependencies:
      - target: Wooly
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Wooly.app/Wooly
