name: Wooly
options:
  bundleIdPrefix: com.kylebashour
settings:
  SWIFT_VERSION: 4.2
targets:
  Wooly:
    type: application
    platform: iOS
    deploymentTarget: 11.0
    sources: Sources/Wooly
    dependencies:
      - target: Mammut
  Mammut:
    type: framework
    platform: iOS
    deploymentTarget: 11.0
    sources: Sources/Mammut
